[#153] Implement Confirmation Popup Component
SE701Team2/Updog pull request #190
Opened 2022-03-27 12:03 UTC by uoa-lzha989

# Description:
Fixes issue #153 

Have added a confirmation popup component for simple yes/no queries. This includes a view, a controller, and the relevant stylings needed. 

When it is being used, then there are four props to be considered: `question`, `open`, `onAccept`, `onDecline`. I don't expect onDecline to do more than dismiss the view, but I would say that it is better for us to pass through the action we want to take for onDecline and allow its control to be set up elsewhere rather than in the component to allow for that modularity. 

![image](https://user-images.githubusercontent.com/68832471/160280469-2d630d75-ce49-41ea-9cba-531be10cc429.png)

^^ A visual of it as an overlay over the profile settings.

### All Submissions:

* [ ] Have you followed the guidelines in our [Contributing document](../CONTRIBUTING.md)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] My code follows the code style of this project
- [ ] My code has been commented
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

2022-03-27 12:11 UTC, uoa-lzha989 commented on frontend/src/components/popup/confirmation/ConfirmationPopUpController.jsx
> +import { useState } from 'react'
I've made mention of this in the Discord, but I'm currently not 100% sure how we would use the controller as most popups are just layered within the jsx, but I've just left it here - should be relatively straightforward in any respect, and would be faster to delete than rewrite.

2022-03-27 21:01 UTC, KirstyGong approved these changes
LGTM

2022-03-27 21:16 UTC, arathibiju approved these changes
LGTM!

2022-03-27 22:39 UTC, scorpionknifes requested changes
LGTM, just 1 extra file to delete

2022-03-27 22:39 UTC, scorpionknifes commented on package-lock.json
> +}
Seems like you accidentally ran npm install on the root directory, can you delete this file. Thx

2022-03-28 02:31 UTC, scorpionknifes approved these changes

2022-03-28 02:33 UTC, merged