Modify Notifications endpoint
SE701Team2/Updog pull request #194
Opened 2022-03-27 20:41 UTC by colaMeowSY

# Description:
-Added new notification type 'follow' to track new followers.
-Added boolean "read" column to keep track of which notifications have been read. NOTE: An alternative might be adding a new notifications table to track whether notifications have been read, currently a read column has been added to the followers'table, sharedPost, likedPost, and Post(for replies).
-Only return unread notifications when requesting GET/notifications.
-Added tests for existing notifications retrieval method:  check for correct order(Latest to oldest notifications), retrieve unread notifications only.

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing document](../CONTRIBUTING.md)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] My code follows the code style of this project
- [x] My code has been commented
- [x] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [x] I have added tests to cover my changes
- [ ] All new and existing tests passed

2022-03-27 21:50 UTC, uoa-ypec413 requested changes

2022-03-27 21:50 UTC, uoa-ypec413 commented on backend/__tests__/notifications.js
> +      const user1 = await models.users.create({
It might be better to use `Helper.createUser()` and other functions in the Helper class for these tests to make them more readable

2022-03-28 00:26 UTC, uoa-ypec413 approved these changes
LGTM, thanks for changing the tests to use the Helper class :)

2022-03-28 01:28 UTC, DanilLinkov approved these changes
LGTM nice job

2022-03-28 09:06 UTC, merged