[#15] - Password functionality for user, including encryption and validation
SE701Team2/Updog pull request #25
Opened 2022-03-07 02:36 UTC by mdar365

---
name: Pull request
about: Creating a pull request for other contributors to review 
title: ''
labels: ''
assignees: ''
---

# Description:
Please provide a summary of changes made and the relevant issue that has been worked on. Also list any major changes made to project structure/dependencies if applicable

### All Submissions:

* [ ] Have you followed the guidelines in our [Contributing document](../CONTRIBUTING.md)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions:

1. [ ] Does your submission pass tests?
2. [ ] Have you lint your code locally prior to submission?
3. [ ] Have you commented your code?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your core changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2022-03-07 12:01 UTC, wjun856 requested changes

2022-03-07 12:01 UTC, wjun856 commented on backend/server/controllers/user.js
As I cannot comment on unchanged code I'll add a review here, the new line 25 should be changed to:
res.status(500).send({"Error message": error.toString()});

This is to be consistent with #27: [backend/server/controllers/user.js](https://github.com/SE701Team2/Updog/pull/27/files/9c35f5d57efddb9d5147f02d6330e4b864a729e4#diff-4a69cf760e3e8730fe1aaafcb461fb1c90a712006a5c0735c2dfee09977a3c16)

2022-03-07 20:53 UTC, mdar365 commented on backend/server/controllers/user.js
The getUsers endpoint was in the boilerplate code, I think I will remove it since we won't be needing to display _all_ users anyways

2022-03-08 01:21 UTC, jmor528 approved these changes
Looks good, it's clear what functionality is being added and is well tested.

2022-03-08 01:25 UTC, jmor528 commented on backend/server/controllers/user.js
The specifics of error formatting can be handled in another issue. For now, I think this code is fine to pulled.

2022-03-08 01:43 UTC, JL-2644 approved these changes
Looks good. Everything works as intended and all tests pass on my end as well. One thing to note would be to add in package.json scripts: { ... ,"test" : "jest" } so that it runs all tests. Something we could do later I guess.

2022-03-08 02:41 UTC, wjun856 approved these changes

2022-03-08 02:45 UTC, merged