[#47] Add user page
SE701Team2/Updog pull request #84
Opened 2022-03-13 22:04 UTC by BruceZeng1

# Description:
Added user page at user/:username.
Using mock data found in frontend/src/pages/user/mock-data.js.
No Follow button or settings button yet due to no authentication.

### All Submissions:

* [ ] Have you followed the guidelines in our [Contributing document](../CONTRIBUTING.md)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] My code follows the code style of this project
- [ ] My code has been commented
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

2022-03-13 23:21 UTC, skwe902 reviewed
LGTM!

2022-03-13 23:28 UTC, BraveNewWord approved these changes
LGTM

2022-03-13 23:34 UTC, nzbasic requested changes

2022-03-13 23:34 UTC, nzbasic commented on frontend/src/pages/user/UserPageView.jsx
> +            >
You should pass an empty onClick handler from the controller so we can easily add logic later

2022-03-14 00:46 UTC, htom380 approved these changes

2022-03-14 11:00 UTC, Billsong19 approved these changes
LGTM, good work!

2022-03-15 00:39 UTC, henrym25 approved these changes

2022-03-15 00:43 UTC, nzbasic approved these changes

2022-03-15 02:01 UTC, merged